
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ADANA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ADIYAMAN');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('AFYONKARAHÝSAR');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('AÐRI');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('AMASYA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ANKARA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ANTALYA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ARTVÝN');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('AYDIN');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('BALIKESÝR');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('BÝLECÝK');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('BÝNGÖL');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('BÝTLÝS');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('BOLU');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('BURDUR');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('BURSA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ÇANAKKALE');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ÇANKIRI');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ÇORUM');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('DENÝZLÝ');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('DÝYARBAKIR');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('EDÝRNE');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ELAZIÐ');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ERZÝNCAN');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ERZURUM');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ESKÝÞEHÝR');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('GAZÝANTEP');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('GÝRESUN');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('GÜMÜÞHANE');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('HAKKARÝ');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('HATAY');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ISPARTA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('MERSÝN');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ÝSTANBUL');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ÝZMÝR');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('KARS');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('KASTAMONU');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('KAYSERÝ');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('KIRKLARELÝ');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('KIRÞEHÝR');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('KOCAELÝ');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('KONYA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('KÜTAHYA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('MALATYA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('MANÝSA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('KAHRAMANMARAÞ');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('MARDÝN');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('MUÐLA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('MUÞ');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('NEVÞEHÝR');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('NÝÐDE');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ORDU');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('RÝZE');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('SAKARYA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('SAMSUN');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('SÝÝRT');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('SÝNOP');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('SÝVAS');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('TEKÝRDAÐ');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('TOKAT');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('TRABZON');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('TUNCELÝ');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ÞANLIURFA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('UÞAK');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('VAN');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('YOZGAT');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ZONGULDAK');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('AKSARAY');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('BAYBURT');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('KARAMAN');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('KIRIKKALE');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('BATMAN');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ÞIRNAK');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('BARTIN');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('ARDAHAN');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('IÐDIR');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('YALOVA');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('KARABÜK');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('KÝLÝS');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('OSMANÝYE');

	
INSERT INTO PROVINCE (PROVINCE_NAME)
	VALUES ('DÜZCE');

