INSERT INTO PUBLISHING_HOUSE
VALUES (PUBLISHINGHOUSE_SEQ.nextval, 'Remzi Kitap Evi');

INSERT INTO PUBLISHING_HOUSE
VALUES (PUBLISHINGHOUSE_SEQ.nextval, 'Yeni Kitapçý');

INSERT INTO PUBLISHING_HOUSE
VALUES (PUBLISHINGHOUSE_SEQ.nextval, 'Ýletisim Yayýnlarý');
