CREATE SEQUENCE PUBLISHINGHOUSE_SEQ
    MINVALUE 1
    MAXVALUE 999999999999999999999999999
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    

INSERT INTO PUBLISHING_HOUSE
VALUES (PUBLISHINGHOUSE_SEQ.nextval, 'Can Yayýnlarý');

INSERT INTO PUBLISHING_HOUSE
VALUES (PUBLISHINGHOUSE_SEQ.nextval, 'Özgür Yayýnlarý');

INSERT INTO PUBLISHING_HOUSE
VALUES (PUBLISHINGHOUSE_SEQ.nextval, 'YKY');

INSERT INTO PUBLISHING_HOUSE
VALUES (PUBLISHINGHOUSE_SEQ.nextval, 'Dergâh Yayýnlarý');

