CREATE SYNONYM USER_SYN FOR USERS_TABLE;
CREATE SYNONYM AUTHOR_SYN FOR AUTHOR;
CREATE SYNONYM PUBLISHING_HOUSE_SYN FOR PUBLISHING_HOUSE;
CREATE SYNONYM BOOK_SYN FOR BOOK;
CREATE SYNONYM USER_BOOK_ASSIGNMENT_SYN FOR USER_BOOK_ASSIGNMENT;

--select * from USER_SYN;