CREATE VIEW USERS_TABLE_VIEW AS (SELECT Email FROM USERS_TABLE);
CREATE VIEW AUTHOR_TABLE_VIEW AS (SELECT Name,Surname FROM AUTHOR);
CREATE VIEW PUBLISHING_HOUSE_VIEW AS (SELECT Name FROM PUBLISHING_HOUSE);
CREATE VIEW BOOK_VIEW AS (SELECT Name, DateOfIssue FROM BOOK);
CREATE VIEW USER_BOOK_ASSIGNMENT_VIEW AS (SELECT * FROM USER_BOOK_ASSIGNMENT WHERE UserId = 2);

--SELECT * FROM all_views where view_name = 'BOOK_VIEW';
--select * from BOOK_VIEW;