USE [HELP_DESK]
GO

CREATE FUNCTION f_COUNT_OF_DEMAND_FOR_COMPANY_USERID_BY_STATE(@Company_UserId INT)
RETURNS @Result TABLE 
(
	STATE NVARCHAR(15) NULL,
	COUNT_OF_DEMAND INT NULL
)
AS
BEGIN

		INSERT INTO @Result
			SELECT DS.STATE, COUNT(DS.STATE) FROM DEMAND D
				INNER JOIN COMPANY_USER CU ON CU.ID = D.COMPANY_USERID
				INNER JOIN DEMAND_STATE DS ON DS.ID = D.DEMAND_STATEID
		WHERE D.COMPANY_USERID = @Company_UserId
		GROUP BY DS.STATE	

	RETURN

END