USE [HELP_DESK]
GO

CREATE FUNCTION f_GET_DEMAND_BY_PRODUCT_MONTHLY (@Year INT, @Month INT)
RETURNS TABLE
AS
RETURN
	SELECT P.PRODUCT_NAME AS PRODUCT_NAME, COUNT(P.ID) AS TALEP_SAYISI FROM DEMAND D 
		INNER JOIN PRODUCT P ON D.PRODUCTID = P.ID
	WHERE YEAR(D.CREATE_DATE) = @Year AND MONTH(D.CREATE_DATE) = @Month AND D.RECORD_STATUS = 1
	GROUP BY P.PRODUCT_NAME, P.ID
