CREATE FUNCTION f_GET_ALL_DEMAND_URGENCY_FOR_EMPLOYEEID (@EMPLOYEEID AS INT) --ACİLİYETE GÖRE GRUPLA
RETURNS TABLE
AS
RETURN
(
	SELECT
		U.[URGENCY],
		COUNT([ORDER_OF_URGENCYID]) TOTAL_NUM
	FROM
		[dbo].[ORDER_OF_URGENCY] U
	INNER JOIN [dbo].[DEMAND] D 
		ON U.[ID] = D.[ORDER_OF_URGENCYID]
  WHERE D.[EMPLOYEEID] = @EMPLOYEEID
  GROUP BY U.[URGENCY]
  );