 CREATE FUNCTION f_GET_ALL_DEMAND_TYPES_FOR_EMPLOYEEID (@EMPLOYEEID AS INT) --(TİPİNE GÖRE GRUPLA)
 RETURNS TABLE
 AS
 RETURN
 (
	SELECT 
		DT.[TYPE],
		COUNT(D.DEMAND_TYPEID) TOTAL_NUM
	FROM
		[dbo].[DEMAND_TYPE] DT
	INNER JOIN [dbo].[DEMAND] D 
		ON DT.[ID] = D.[DEMAND_TYPEID]
	WHERE D.[EMPLOYEEID] = @EMPLOYEEID
	GROUP BY DT.[TYPE]
);