CREATE FUNCTION f_GET_PRODUCTS_FOR_EMPLOYEE_ID (@EMPLOYEEID AS INT)
RETURNS TABLE 
AS
RETURN 
(
	SELECT 
		PRODUCT_NAME 
	FROM 
		[dbo].[PRODUCT] P
	INNER JOIN [dbo].[PRODUCT_EMPLOYEE_MAPPING] PEM 
		ON P.ID = PEM.PRODUCTID
	WHERE EMPLOYEEID = @EMPLOYEEID	
);