USE [HELP_DESK]
GO

CREATE FUNCTION f_GET_DEMANDS_FOR_COMPANY_USERID(@Company_UserId INT)
RETURNS  @Demands TABLE 
(
    ID INT,
	TITLE NVARCHAR(MAX) NULL,
	[TEXT] NVARCHAR(MAX) NULL,
	DEMAND_TYPEID INT NULL,
	ORDER_OF_URGENCYID INT NULL,
	DEMAND_STATEID INT NULL,
	CLOSING_STATEMENT NVARCHAR(MAX) NULL,
	CLOSING_DATE  DATETIME NULL,
	COMPANY_USERID INT NOT NULL,
	EMPLOYEEID INT NULL,	
	PRODUCTID INT NOT NULL,
	SOLVED_HOUR INT NULL,
	VERSIONID INT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	MODIFICATION_DATE DATETIME NOT NULL,
	RECORD_STATUS BIT DEFAULT 1
)
AS
BEGIN

		INSERT INTO @Demands
			SELECT D.* FROM DEMAND D
				INNER JOIN COMPANY_USER CU ON CU.ID = D.COMPANY_USERID
		WHERE D.COMPANY_USERID = @Company_UserId		

	RETURN

END