USE [HELP_DESK]
GO

CREATE FUNCTION f_GET_DEMAND_BY_COMPANY_MONTHLY (@Year INT, @Month INT)
RETURNS TABLE
AS
RETURN
	SELECT C.COMPANY_NAME AS COMPANY_NAME, COUNT(C.ID) AS DEMAND_COUNT FROM DEMAND D 
		INNER JOIN COMPANY_USER CU ON D.COMPANY_USERID = CU.ID
		INNER JOIN COMPANY C ON C.ID = CU.COMPANYID
		WHERE D.RECORD_STATUS = 1 AND C.RECORD_STATUS = 1
			  AND YEAR(D.CREATE_DATE) = @Year AND MONTH(D.CREATE_DATE) = @Month
		GROUP BY C.COMPANY_NAME, C.ID
	
