-- SYSTEM ADMIN URUNLERI GORUNTULEYEBILIR--

CREATE VIEW vw_GET_ALL_PRODUCT
AS

SELECT P.ID,P.PRODUCT_NAME,LP.PERIOD,V.VERSIONNO FROM PRODUCT P 
INNER JOIN LICENSE_PERIOD LP ON P.LICENSE_PERIODID = LP.ID
INNER JOIN [VERSION] V ON P.ID = V.PRODUCTID
