CREATE VIEW vw_GET_ALL_DEMAND_WITH_NAMES AS
	SELECT D.ID, D.TITLE, D.TEXT, DT.TYPE, DS.STATE, OU.URGENCY, 
		CONCAT(CU.COMPANY_USER_NAME, ' ', CU.COMPANY_USER_SURNAME) AS COMPANY_USER,
		CONCAT(E.EMPLOYEE_NAME, ' ', E.EMPLOYEE_SURNAME) AS EMPLOYEE,
		P.PRODUCT_NAME, D.SOLVED_HOUR, V.VERSIONNO, D.CREATE_DATE, D.MODIFICATION_DATE, D.RECORD_STATUS
	FROM DEMAND D
		INNER JOIN DEMAND_STATE DS ON DS.ID = D.DEMAND_STATEID
		INNER JOIN ORDER_OF_URGENCY OU ON OU.ID = D.ORDER_OF_URGENCYID
		INNER JOIN DEMAND_TYPE DT ON DT.ID = D.DEMAND_TYPEID
		INNER JOIN COMPANY_USER CU ON CU.ID = D.COMPANY_USERID
		INNER JOIN EMPLOYEE E ON E.ID = D.EMPLOYEEID
		INNER JOIN PRODUCT P ON P.ID = D.PRODUCTID
		INNER JOIN VERSION V ON V.ID = D.VERSIONID


